// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(['underscore', 'backbone', 'models/appState'], function(_, Backbone, AppState) {
    var Utilities;
    Utilities = (function() {
      function Utilities() {
        this.buildDeviceInfo = __bind(this.buildDeviceInfo, this);
        this.buildDatetime = __bind(this.buildDatetime, this);
        this.toISOString = __bind(this.toISOString, this);
        this.datetimeHelper = __bind(this.datetimeHelper, this);
        this.newDateHelper = __bind(this.newDateHelper, this);
        this.fuzzyHelper = __bind(this.fuzzyHelper, this);
        this.weekdayHelper = __bind(this.weekdayHelper, this);
        this.log = __bind(this.log, this);
        this.dateRegex = /\d{2,4}[-]\d{2}[-]\d{2}/i;
        this.timeRegex = /\d{1,2}[:]\d{2}[:]\d{2}/i;
      }

      Utilities.prototype.operators = {
        "+": function(left, right) {
          return parseInt(left, 10) + parseInt(right, 10);
        },
        "-": function(left, right) {
          return parseInt(left, 10) - parseInt(right, 10);
        }
      };

      Utilities.prototype.log = function() {
        var args, argument, _i, _len;
        args = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          argument = arguments[_i];
          if (typeof argument === 'object') {
            argument = JSON.stringify(argument);
          }
          args.push(argument);
        }
        return console.log(args.join(" "));
      };

      Utilities.prototype.weekdayHelper = function(dayOfWeek) {
        var currentDate, currentDay, date, offset;
        this.log('weekday helper', dayOfWeek);
        date = new Date();
        currentDay = date.getDay();
        currentDate = date.getDate();
        offset = currentDay < dayOfWeek ? dayOfWeek - currentDay : 7 - (currentDay - dayOfWeek);
        date.setDate(currentDate + offset);
        return date;
      };

      Utilities.prototype.fuzzyHelper = function(datetime, isDate) {
        var date, datetimeArr, def, key, label, preference, splitSym, val;
        this.log('fuzzy helper', datetime, isDate);
        date = new Date();
        this.log('handle fuzzy date or time');
        for (key in datetime) {
          val = datetime[key];
          this.log(key, val);
          if (key === 'label') {
            label = val;
          }
          if (key === 'default') {
            def = val;
          }
        }
        preference = def;
        this.log('use', preference);
        if (preference === null) {
          this.log('useTime error');
          return;
        }
        splitSym = isDate === true ? '-' : ':';
        datetimeArr = preference.trim().split(splitSym);
        if (isDate === true) {
          date.setFullYear(datetimeArr[0]);
          date.setMonth(datetimeArr[1] - 1);
          date.setDate(datetimeArr[2]);
        } else {
          date.setHours(datetimeArr[0]);
          date.setMinutes(datetimeArr[1]);
          date.setSeconds(datetimeArr[2]);
        }
        return date;
      };

      Utilities.prototype.newDateHelper = function(datetime) {
        var hours, minutes, newDate, seconds, split;
        this.log('newDate', datetime);
        if (datetime.indexOf('now') !== -1) {
          this.log('is now');
          newDate = new Date();
        } else if (this.dateRegex.test(datetime) === true) {
          this.log('is date string');
          split = datetime.split('-');
          newDate = new Date(split[0], split[1] - 1, split[2]);
        } else if (this.timeRegex.test(datetime) === true) {
          this.log('is time');
          newDate = new Date();
          split = datetime.split(':');
          hours = newDate.getHours();
          minutes = newDate.getMinutes();
          seconds = newDate.getSeconds();
          if ((hours > split[0]) || (hours === split[0] && minutes > split[1])) {
            newDate.setDate(newDate.getDate() + 1);
          }
          newDate.setHours(split[0]);
          newDate.setMinutes(split[1]);
          newDate.setSeconds(split[2]);
        }
        this.log('newDate bottom', newDate);
        if (newDate === null || newDate === void 0) {
          return new Date();
        } else {
          return newDate;
        }
      };

      Utilities.prototype.datetimeHelper = function(dateOrTime, newDate) {
        var action, curr, date, interval, isDate, item, itemKey, itemValue, operator, parsable, time, _i, _len;
        if (newDate == null) {
          newDate = null;
        }
        this.log(dateOrTime);
        if (_.isString(dateOrTime)) {
          this.log('is string');
          if (_.isNull(newDate)) {
            newDate = this.newDateHelper(dateOrTime);
          }
        } else if (_.isObject(dateOrTime)) {
          this.log('is object');
          for (action in dateOrTime) {
            parsable = dateOrTime[action];
            this.log('step 1', action, parsable);
            if (action.indexOf('weekday') !== -1) {
              return this.weekdayHelper(parsable);
            } else if (action.indexOf('fuzzy') !== -1) {
              isDate = action.indexOf('date') !== -1 ? true : false;
              return this.fuzzyHelper(parsable, isDate);
            } else {
              operator = action.indexOf('add') !== -1 ? '+' : '-';
              if (_.isArray(parsable)) {
                for (_i = 0, _len = parsable.length; _i < _len; _i++) {
                  item = parsable[_i];
                  if (_.isNull(newDate)) {
                    this.log('step 2', 'set datetime');
                    if (_.isString(item)) {
                      newDate = this.newDateHelper(item);
                    } else if (_.isObject(item)) {
                      for (itemKey in item) {
                        itemValue = item[itemKey];
                        if (newDate === null) {
                          if (itemKey.indexOf('weekday') !== -1) {
                            newDate = this.weekdayHelper(itemValue);
                          } else if (itemKey.indexOf('fuzzy') !== -1) {
                            isDate = itemKey.indexOf('date') !== -1 ? true : false;
                            newDate = this.fuzzyHelper(itemValue, isDate);
                          }
                        }
                      }
                    }
                  } else if (_.isNumber(item)) {
                    this.log('step 3', 'parse array group');
                    interval = item;
                    if (interval === null) {
                      this.log('frag error', interval);
                      return;
                    }
                    if (action.indexOf('time') !== -1) {
                      curr = newDate.getSeconds();
                      time = this.operators[operator](curr, interval);
                      newDate.setSeconds(time);
                    } else if (action.indexOf('date') !== -1) {
                      curr = newDate.getDate();
                      date = this.operators[operator](curr, interval);
                      newDate.setDate(date);
                    }
                  }
                }
              }
            }
          }
        }
        return newDate;
      };

      Utilities.prototype.toISOString = function(dateObj) {
        var pad;
        pad = function(number) {
          var r;
          r = String(number);
          if (r.length === 1) {
            r = '0' + r;
          }
          return r;
        };
        return dateObj.getFullYear() + '-' + pad(dateObj.getMonth() + 1) + '-' + pad(dateObj.getDate()) + 'T' + pad(dateObj.getHours()) + ':' + pad(dateObj.getMinutes()) + ':' + pad(dateObj.getSeconds());
      };

      Utilities.prototype.buildDatetime = function(date, time) {
        var dateObj, dateString;
        dateObj = null;
        this.log('start date parsing');
        if (date !== null) {
          dateObj = this.datetimeHelper(date);
        }
        this.log('start time parsing');
        if (time !== null) {
          dateObj = this.datetimeHelper(time, dateObj);
        }
        dateString = this.toISOString(dateObj).split('T');
        return {
          date: dateString[0],
          time: dateString[1]
        };
      };

      Utilities.prototype.buildDeviceInfo = function() {
        var clientDate, deviceInfo;
        clientDate = new Date();
        return deviceInfo = {
          "latitude": AppState.get('lat'),
          "longitude": AppState.get('lon'),
          "timestamp": clientDate.getTime() / 1000,
          "timeoffset": -clientDate.getTimezoneOffset() / 60
        };
      };

      return Utilities;

    })();
    return new Utilities();
  });

}).call(this);
